<?php

namespace ContainerXFBVxZd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploaderHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\UploaderHelper' shared autowired service.
     *
     * @return \App\Service\UploaderHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service "App\\Service\\UploaderHelper": argument "$uploadsPath" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
