<?php

namespace ContainerYGeL1Jn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ALM9o_0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aLM9o.0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aLM9o.0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'trick' => ['privates', '.errored..service_locator.aLM9o.0.App\\Entity\\Trick', NULL, 'Cannot autowire service ".service_locator.aLM9o.0": it references class "App\\Entity\\Trick" but no such service exists.'],
            'uploaderHelper' => ['privates', 'App\\Service\\UploaderHelper', 'getUploaderHelperService', true],
        ], [
            'trick' => 'App\\Entity\\Trick',
            'uploaderHelper' => 'App\\Service\\UploaderHelper',
        ]);
    }
}
