<?php

namespace Container5FV70aV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrick3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uCPkpc0.App\Entity\Trick' shared service.
     *
     * @return \App\Entity\Trick
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.uCPkpc0": it references class "App\\Entity\\Trick" but no such service exists.');
    }
}
