<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9j1Whlx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9j1Whlx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9j1Whlx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9j1Whlx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9j1Whlx\App_KernelDevDebugContainer([
    'container.build_hash' => '9j1Whlx',
    'container.build_id' => '28b31bb0',
    'container.build_time' => 1611839273,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9j1Whlx');
