<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWthLJgC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWthLJgC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWthLJgC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWthLJgC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWthLJgC\App_KernelDevDebugContainer([
    'container.build_hash' => 'WthLJgC',
    'container.build_id' => 'e3a70bb8',
    'container.build_time' => 1611910997,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWthLJgC');
