<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7hsTQL9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7hsTQL9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7hsTQL9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7hsTQL9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7hsTQL9\App_KernelDevDebugContainer([
    'container.build_hash' => '7hsTQL9',
    'container.build_id' => '305778b4',
    'container.build_time' => 1612434183,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7hsTQL9');
