<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'js/app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~js/app.js',
                '/build/js/app.js',
            ],
        ],
        'js/add-trick' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~js/add-trick~js/edit-trick.js',
                '/build/js/add-trick.js',
            ],
        ],
        'js/edit-trick' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~js/add-trick~js/edit-trick.js',
                '/build/js/edit-trick.js',
            ],
        ],
        'css/base' => [
            'js' => [
                '/build/runtime.js',
            ],
        ],
        'css/app' => [
            'js' => [
                '/build/runtime.js',
            ],
        ],
    ],
],

]];
